sudo: false
dist: trusty
language: node_js
# node version is specified using the .nvmrc file
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
addons:
  firefox: latest
  chrome: stable

